/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutN: typeof import('./src/components/AboutN.vue')['default']
    ChangeGuys: typeof import('./src/components/Abilitys/ChangeGuys.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OutGuys: typeof import('./src/components/Abilitys/OutGuys.vue')['default']
    PlayGuys: typeof import('./src/components/Abilitys/PlayGuys.vue')['default']
    RadarChart: typeof import('./src/components/RadarChart.vue')['default']
    RealtyGuys: typeof import('./src/components/Abilitys/RealtyGuys.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrongGuys: typeof import('./src/components/Abilitys/StrongGuys.vue')['default']
    TestEnd: typeof import('./src/components/TestEnd.vue')['default']
    TestN: typeof import('./src/components/TestN.vue')['default']
    WeridGuys: typeof import('./src/components/Abilitys/WeridGuys.vue')['default']
  }
}
